name: Build and Release on Tag Push

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-20.04

    outputs:
      TARGET: ${{ steps.set_variable.outputs.TARGET }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Make
        run: sudo apt-get install build-essential

      - name: Build Project
        run: make

      - name: Set buildinfo
        run: |
          echo "TARGET=`gcc -dumpmachine`" >> $GITHUB_ENV
          gcc -v
          echo $GITHUB_ENV
          cat $GITHUB_ENV


      - name: Upload Artifact
        id: upload-artifact
        uses: actions/upload-artifact@v2
        with:
          name: l2h-binary
          path: l2h

  release:
    needs: build
    name: Create Release
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Release Name
        id: set_release_name
        run: echo "RELEASE_NAME=Release $TARGET-${{ github.ref }}" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ env.RELEASE_NAME }}
          draft: false
          prerelease: false

      - name: Download Release Asset
        id: download-release-asset
        uses: actions/download-artifact@v2
        with:
          name: l2h-binary
          path: .

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: l2h
          asset_name: l2h-binary
          asset_content_type: application/octet-stream

